version: '3.8'
services:
  web:
    build: .
    container_name: myapp_container
    ports:
      - "80:80" # Maps port 80 on the host to port 80 in the container
    environment:
      - NODE_ENV=production